### ISSUE TITLE
Error with calculations

### ISSUE THREAD

**Issue by asaurabh-iitk** [dylanwal/unitpy#10]
I'm trying this:

```python
tcA = 31 * Unit.degC
mT = 38.1 * Unit.degC
print(mT - tcA)
```
Apparently, the answer is -266.05 Celsius ! What happened?

**Comment by dylanwal** [comment]
Temperature units like degC and degF have an offset from zero which makes doing math with these types of units different than any other. The default behavior is to do calculations as absolute values (kelvin). To do relative calculations try:
```
tcA = 31 * Unit.degC
mT = 38.1 * Unit.degC
print(mT.sub_rel(tcA))   # 7.1 degC
``` 

There is also an '.add_rel' too.

**Comment by asaurabh-iitk** [comment]
Thanks, but even with the default behavior of converting to Kelvin, the answer should not be -266.05 with unit celsius.

**Comment by dylanwal** [comment]
The -266.05 degC comes from working on the absolute scale:
38.1 degC - 31 degC =  311.25 K - 304.15 K = 7.1 K = -266.05 degC
