### ISSUE TITLE
Prefixes don't work for all units

### ISSUE THREAD

**Issue by CodingBobby** [dylanwal/unitpy#9]
Using prefixes like milli or kilo doesn't work for some units. For example, `10*U.ms` is correctly interpreted as `Quantity(10, 'millisecond')`, but `10*U.mbar` gives a ValueError 'Unexpected character at position 0' instead of `Quantity(10, 'millibar')`.

I tested some other units and found that `hour` and `minute` also don't accept prefixes – which would be uncommon to do, I understand that – but `calorie_th`,  `bar`, `parsec`, `electronvolt` (and probably more) which are very often used with prefixes do fail as well. 

I tried using the prefixes in several ways like `U.mbar`, `U('mbar')`, `U('millibar')` and `U('milli bar')`. None of them work. I'm aware, that the prefix can be used by simply multiplying the quantity's value with the respective factor, but in my case I needed to have the unit including the prefix saved in a separate variable.

Why don't the prefixes work for all units? Or am I missing something here and they can be used in a different way?

**Comment by dylanwal** [comment]
I believe it prefixes should work for all units. I will look into it.

**Comment by dylanwal** [comment]
I fix the bugs and prefixes should be working for all units (in v0.0.18).
Thanks again for letting me know!

**Comment by CodingBobby** [comment]
It works with the new version. Thanks a lot for the quick fix!
